mtc/driver:
  ros__parameters:
    #robot_id: "F535AF9628574A53"
    #robot_id: "3536AF962E7A4A53"
    robot_id: "7536AF961D784A53"
    #ip: "192.168.68.188"
    #ip: "192.168.68.151"
    #ip: "192.168.68.134"
    ip: "192.168.68.202"
    sensor_timer_period_s: 0.1
    max_r: 2.0

mtc/astar_controller:
  ros__parameters:
    cell_total_size: [0.192, 0.192]
    sim: false
    angle_th: 0.25
    fwd_th: 0.1
    avoid_lim: -1
    stuck_mp: 5.

mtc/slam:
  ros__parameters:
    lab_size: [16, 16]
    cell_size: [0.168, 0.168]
    pile_size: 0.024 # 0.12
    start_pose: [0.084, 0.084, 1.5708]
    start_pose_sigma: [0.01, 0.01, 0.01]
    n_particles: 500
    wall_th: 0.5
    alpha: [0.1, 0.01, 0.1, 0.01, 0.5, 0.5]
    n_updates: 4
    #alpha: [.0, .0, .0, .0, .0, .0]
    range_sigma: 0.01
    max_r: 2.0

    on_wall_th: 7.0 # in parts of cell_size[0]
    wall_clear_th: 2.0 # in parts of cell_size[0]
