mtc/driver:
  ros__parameters:
    ranges_sigma: 0.1
    start_x: 0.91
    start_y: 0.91
    start_yaw: -1.5708
    

mtc/slam:
  ros__parameters:
    lab_size: [16, 16]
    cell_size: [1.50, 1.50]
    pile_size: 0.165
    start_pose: [0.91, 0.91, 1.5708]
    start_pose_sigma: [0.02, 0.02, 0.01]
    n_particles: 500
    wall_th: 0.75
    alpha: [0.75, 0.05, 0.75, 0.05, 0.1, 0.1]
    n_updates: 4
    #alpha: [.0, .0, .0, .0, .0, .0]
    range_sigma: 0.1
    on_wall_th: 8
    wall_clear_th: 2

mtc/carrot_standalone:
  ros__parameters:
    distance_tolerance: 0.36
    angle_tolerance: 0.52
    min_cmd_angle: 0.35
    max_cmd_angle: 6.28
    min_cmd_dist: 0.1
    max_cmd_dist: 0.9
